global:
  scrape_interval: 15s # Default scrape interval

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'railway_cost_exporter'
    scrape_interval: 1m
    static_configs:
      - targets:
          - 'railway-cost-exporter:8080'
