global:
  scrape_interval: 15s # Default scrape interval
  scrape_timeout: 5s
  evaluation_interval: 15s
  
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'n8n-local'
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'primary-production-b2e2d:5678'
